# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoclase',
            old_name='num_meeting',
            new_name='meeting_id',
        ),
    ]
