# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videoclase', '0004_auto_20170906_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclasefprop',
            name='numero_de_meeting',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoclasefprop',
            name='descarga',
            field=models.URLField(verbose_name='Archivo de Descarga'),
        ),
    ]
