# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclase', '0005_auto_20170906_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_meeting', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='videoclasefprop',
            name='numero_de_meeting',
        ),
    ]
