# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclase', '0007_auto_20170906_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=30), max_length=100),
        ),
    ]
